name: .NET Core Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: |
        dotnet nuget add source --username rafael-rm --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rafael-rm/index.json"
        dotnet restore
      
    - name: Package generation
      run: dotnet build -c Release
    
    - name: Upload package
      run: |
        find . -name "*.nupkg" -exec dotnet nuget push {} --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/rafael-rm/index.json" --skip-duplicate \;
